#!/bin/bash
version="1.3"
bold=$( tput bold )
normal=$( tput sgr0 )

help () {
	tput bold
	echo "note"
	echo "     -r <note name>: Read a note."
	echo "     -n <note name>: Write a new note."
	echo "     -l: Show all notes."
	echo "     -cname <note name> <new note name>: Change the note name."
	echo "     -d <note name>: Delete Note."
	echo "     -dAll: Delete all notes."
	echo "     -i: Shows some information about this tool."
	echo "     -h: Show this message."
	tput sgr0
}

listNotes () {
	tput bold
	tput sgr0
	lsNotes=$( ls /usr/share/jlnote/notes/ | while IFS= read -r line ; do 
    echo "$line"
	done )
	if [ -z $lsNotes ]; then
		tput bold
		echo "You dont have any notes."
		tput sgr0
	else
		tput bold
		echo -en "your notes: \n"
		tput sgr0
		echo "${lsNotes}"
	fi
}

if [ -z $1 ]; then
	help
else
	case $1 in
	-r)
		noteName="$2"
		
		noteContent=$(cat "/usr/share/jlnote/notes/${noteName}")
		if [ -z $noteName ]; then
		  	echo -en "note name: "
		  	read -r noteName
		fi
		echo "${bold}note:${normal} $noteContent";;
	-n)
		if [ -z "${2}" ]; then
			tput bold
			echo -en "note name: "
			tput sgr0
			read -r newNoteName
		else
			newNoteName="${2}"
		fi
		if ! [ -z "${3}" ]; then
			echo "The name has to have no spaces."
			exit 1
		fi			
		if [ -f /usr/share/jlnote/notes/$newNoteName ]; then
			echo "That note name is already used. Please choose a new one."
			exit 1
		fi
		tput bold
		echo -en "note content: "
		tput sgr0

		noteDir="/usr/share/jlnote/notes/"

		read -r newNoteContent
		echo "$newNoteContent" > ${noteDir}${newNoteName}
		tput bold
		echo "NOTE SAVED"
		tput sgr0;;	
	-cname)
		changeName="${2}" 
		changeNewName="${3}"

		if [ -z $changeName ]; then
			tput bold
			echo -en "Which note name do you want to change? "
			tput sgr0
			read -r changeName
		fi
		if [ -z $changeNewName ]; then
			tput bold
			echo -en "What would you like to change the name to? "
			tput sgr0
			read -r changeNewName
		fi
		if ! [ -z "${changeNewName}" ]; then
			tput bold
			echo "The name has to have no spaces."
			tput sgr0
			exit 1
		fi			
		if [ -f /usr/share/jlnote/notes/$changeNewName ]; then
			tput bold
			echo "That note name is already used. Please choose a new one."
			tput sgr0
			exit 1
		fi
		cp "/usr/share/jlnote/notes/${changeName}" "/usr/share/jlnote/notes/${changeNewName}"
		;;
	-d)
		if [ -z $2 ]; then
			tput bold
			echo -en "note name: "
			tput sgr0
			read deleteNoteName
		else
			deleteNoteName="$2"
		fi
		if ! [ -f /usr/share/jlnote/notes/${deleteNoteName} ]; then
			tput bold
			echo "The note doesnt exists."
			tput bold
			exit 1
		fi
		rm /usr/share/jlnote/notes/${deleteNoteName}
		echo "NOTE DELETED";;
	-dAll)
		tput bold
		echo "Are you sure you want to delete all note? Y or N"
		tput sgr0
		read yOrNo
		case $yOrNo in
			Y )
				rm /usr/share/jlnote/notes/*
				tput bold
				echo "All notes were deleted."
				tput sgr0;;
			* )
				tput bold
				echo "No notes were deleted."
				tput sgr0;;
		esac;;
	-l)
		listNotes;;
	-ls)
		listNotes;;
	-h)
		help;;
	-i)
		printf "${bold}JLNote is a minimalistic tool coded in Bash for one line notes. Created by Christian Gerlin Joyggy.\nJLNote is an abbreviation for Joyggy's Linux Note Tool${normal}";;
	*)
		tput bold
		echo "invalid parameter. Those are the valid parameters:"
		tput sgr0
		help;;
	esac
fi
